### ISSUE TITLE
Pydantic v2 Migration

### ISSUE THREAD

**Issue by fritzdj** [jtc42/fastapi-hypermodel#32]
@jtc42, I saw you added a comment clarifying that this is intended to be compatible with pydantic v1. Are you planning on keeping this constrained to >=1.8.0, <2.0.0? Or can we add something like the logic below to use the "v1 API" that is still supported by pydantic with v2 ([see docs](https://docs.pydantic.dev/latest/migration/#continue-using-pydantic-v1-features))? e.g.
```
from pydantic.version import VERSION as PYDANTIC_VERSION

if PYDANTIC_VERSION.startswith("2."):
  from pydantic.v1 import BaseModel 
else:
  from pydantic import BaseModel 
```

**Comment by jtc42** [comment]
Hey! Yeah sorry about the v2 development stalling, I was trying to port it "properly" and it ended up taking more time than I have available right now, and still not working.

If the v1 API allows it to still work with v2 I'm more than happy to go down that route. If someone raises a PR and everything passes, I'll gladly merge. Otherwise, I'll try and get round to implementing and testing it in the near future (though that's intentionally vague as I've no idea when it's likely to be).

**Comment by fritzdj** [comment]
> Hey! Yeah sorry about the v2 development stalling, I was trying to port it "properly" and it ended up taking more time than I have available right now, and still not working.
> 
> If the v1 API allows it to still work with v2 I'm more than happy to go down that route. If someone raises a PR and everything passes, I'll gladly merge. Otherwise, I'll try and get round to implementing and testing it in the near future (though that's intentionally vague as I've no idea when it's likely to be).

No worries @jtc42, thanks for the reply! I think there is not a lot of value with using the pydantic "v1 API" (`pydantic.v1.*`) because FastAPI is not currently supporting this as a valid migration path: https://github.com/tiangolo/fastapi/discussions/9966.

**Comment by jtc42** [comment]
Seehttps://github.com/jtc42/fastapi-hypermodel/releases/tag/v2.0.0
